services:
  ai-gen:
    build:
      context: ./ai
      dockerfile: Dockerfile
    image: chat-lab-ai-gen
    volumes:
      - ./ai:/app
    user: "${D_UID}:${D_GID}"
    environment:
      - PYTHONUNBUFFERED=1