services:
  ai-gen:
    build:
      context: ./ai
      dockerfile: Dockerfile
    image: chat-lab-ai-gen
    volumes:
      - ./ai:/app
    user: "${D_UID}:${D_GID}"
    environment:
      - PYTHONUNBUFFERED=1

  chat-lab:
    build:
      context: .
      dockerfile: app.Dockerfile
    image: chat-lab-app
    depends_on:
      - ai-gen
    volumes:
      - .:/app
      - /tmp/badger:/tmp/badger
    user: "${D_UID}:${D_GID}"
    env_file:
      - cmd/master/chat.conf  # Docker va charger toutes les variables de ce fichier
    environment:
      - HOST=127.0.0.1
      - PORT=8080
      - TOXICITY_BIN_PATH=/usr/local/bin/specialist
      - SENTIMENT_BIN_PATH=/usr/local/bin/specialist
      - TOXICITY_PORT=8081
      - SENTIMENT_PORT=8082
      - BADGER_FILEPATH=/tmp/badger
    ports:
      - "8080:8080"